version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: |
            coverage run --branch -m pytest -v
            coverage report
            coverage html
          name: Test
      - store_test_results:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
