version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Test
          command: mvn verify
      - run:
          name: Store test results
          command: |
            mkdir test-results
            cp target/surefire-reports/*.xml test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: target/site/jacoco
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  main:
    jobs:
      - build-and-test
